### ISSUE TITLE
Follow ups for refactor of frame buffer code and enable two-threaded rendering

### ISSUE THREAD

**Issue by bghgary** [BabylonJS/BabylonNative#638]
https://github.com/BabylonJS/BabylonNative/pull/591

- [x] File issue for TODO in NativeEngine::DeleteVertexArray
- [x] File issue for loading Draco scripts (Filed as #1214)
- [ ] <strike>File issue for macOS validation tests will sometimes hang</strike>
- [x] File issue for bgfx leak when shutting down without calling engine.dispose. Can be fixed in NativeEngine destructor with some refactoring.
- [x] File issue to add validation tests that include shutdown scenarios. (Filed as #1215)
- [x] Resizing (Win32, UWP, macOS) is messed up. (Win32 / UWP have been addressed mostly. macOS seems okay.)
- [x] File issue for MATERIAL_TriangleFanDrawMode not being supported by bgfx. (Filed as #1216)
- [x] Consider using `CompositionTarget::Rendering` in UWP. (FIled as #1217)
- [ ] <strike>Investigate possible threading issue in NativeXr::BeginUpdate() as per [comment] (https://github.com/BabylonJS/BabylonNative/pull/591/files/bc9c6b639b2269e636dbd10aa91114d3ebd13753#r588769543) </strike>. (Haven't seen any issues with this)
- [x] Investigate async initialization (e.g. removal of _whenGraphicsReady and how that will work in the future)

**Comment by bghgary** [comment]
Opened new issues for ones that are still relevant and updated OP with links to the new issues.
