### ISSUE TITLE
[GLTF] Validation Tests

### ISSUE THREAD

**Issue by CedricGuillemet** [BabylonJS/BabylonNative#811]
BabylonJS list of validation tests here : https://github.com/BabylonJS/Babylon.js/blob/master/tests/validation/config.json

- [x] GLTF Normals
- [x] GLTF Animation Node
- [x] GLTF Animation Node Misc
- [x] GLTF Animation Skin (0) 
- [x] GLTF Animation Skin (1)
- [x] GLTF Animation Skin Type
- [x] GLTF Buffer Interleaved 
- [x] GLTF Material
- [x] GLTF Material Alpha Blend
- [x] GLTF Material Alpha Mask
- [x] GLTF Material Double Sided (Front)
- [x] GLTF Material Double Sided (Back)
- [x] GLTF Material Metallic Roughness (0)
- [x] GLTF Material Metallic Roughness (1)
- [x] GLTF Material Mixed
- [x] GLTF Material Specular Glossiness (0)
- [x] GLTF Material Specular Glossiness (1)
- [x] GLTF Mesh Primitive Attribute
- [x] GLTF Mesh Primitive Mode (0)
- [x] GLTF Mesh Primitive Mode (1) 
- [x] GLTF Mesh Primitive Vertex Color
- [x] GLTF Mesh Primitives
- [x] GLTF Mesh Primitives UV (0) 
- [x] GLTF Mesh Primitives UV (1)
- [x] GLTF Node Attribute (0)
- [x] GLTF Node Attribute (1)
- [x] GLTF Node NegativeScale (0)
- [x] GLTF Node NegativeScale (1)
- [x] GLTF Texture Sampler (0)
- [x] GLTF Texture Sampler (1)
- [x] GLTF Sheen
- [x] GLTF ClearCoat
- [x] GLTF Alpha Blend
- [ ] ~GLTF Buggy with Draco Mesh Compression~ See #1214
- [ ] ~GLTF Buggy with Meshopt Compression~ See #1214
- [x]  GLTF BoomBox with Unlit Material
- [x] GLTF Extension KHR_texture_transform
- [ ] ~GLTF Extension KHR_materials_volume~ Superseded by #1421
- [x] GLTF Extension KHR_materials_volume with attenuation
- [x] GLTF Extension KHR_materials_specular
- [x] GLTF Texture Linear Interpolation Test
- [ ] ~GLTF Mesh Primitive Attribute Test~ See #1216
- [x] GLTF Extension EXT_mesh_gpu_instancing
- [x] GLTF Extension KHR_materials_variants 
- [x] GLTF ext MSFT_LOD
- [x] Iridescence
<strike>- [ ] GLTF Serializer with Negative World Matrix</strike>
<strike>- [ ] GLTF Serializer with Negative World Matrix (Right Handed)</strike>
<strike>- [ ] GLTF Serializer Skinning and Animation</strike>
<strike>- [ ] GLTF Serializer Skinning and Animation (Right Handed)</strike>
<strike>- [ ] GLTF Serializer Morph Target Animation</strike>
<strike>- [ ] GLTF Serializer Morph Target Animation Group</strike>
<strike>- [ ] GLTF Serializer KHR materials clearcoat</strike>

**Comment by CedricGuillemet** [comment]
4 tests added with this PR : https://github.com/BabylonJS/BabylonNative/pull/812

**Comment by CedricGuillemet** [comment]
4 more : https://github.com/BabylonJS/BabylonNative/pull/815

**Comment by CedricGuillemet** [comment]
2 more tests with https://github.com/BabylonJS/BabylonNative/pull/1344

**Comment by bghgary** [comment]
For the WebAssembly ones, we are probably only going to support in V8 or engines that already have WebAssembly support.

**Comment by bghgary** [comment]
Closing since everything not done is represented by other issues now.
